### ISSUE TITLE
This game sucks

### ISSUE THREAD

**Issue by yarez** [chocokitty24/MazeGame#1]
I loaded up the game, and it compiled correctly, but I didn't have any fun. 

Attached screenshot of the game sucking
![capture](https://cloud.githubusercontent.com/assets/13985515/10737206/45ec2bb2-7be7-11e5-9664-8ff90e11f725.PNG)

Also this game promotes drug use, which is so bad it retroactively made my kids addicted to drugs for years before even playing it. I'm pursuing legal action.

**Comment by chocokitty24** [comment]
You can fix this issue by not being a little Bitch.
